[package]
name = "infopro1"
version = "0.1.0"
authors = ["alexander sanchez <asanchez.dev@gmail.com>"]

# [profile.dev]
# codegen-units = 4

[dependencies]
rust-crypto = "^0.2"
rand = "*"
# num = "*"
time = "*"
rayon = "*"
uuid = { version = "0.2", features = ["serde", "v4"]}
